export enum FontSize {
    xxxxxSmall = 6,
    xxxxSmall = 8,
    xxxSmall = 10,
    xxSmall = 12,
    xSmall = 14,
    Small = 16,
    Regular=18,
    Large = 20,
    xLarge = 22,
    xxLarge = 24,
    xxxLarge = 26,
    xxxxLarge = 28,
    xxxxxLarge = 30,
    xxxxxxLarge = 34,
    xxxxxxxLarge = 38,
    xxxxxxxxLarge = 42,
    xxxxxxxxxLarge = 50,

}